// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoTWoWsC2ngHtEotoW-LXfj6u10sgvNJI',
    appId: '1:713159073959:web:cee94adc0919aee9b8fb82',
    messagingSenderId: '713159073959',
    projectId: 'crudfirey',
    authDomain: 'crudfirey.firebaseapp.com',
    storageBucket: 'crudfirey.appspot.com',
    measurementId: 'G-6VZXEHHW7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQO2eMsEGNVUS_J9grkNvbIkE5iJa7gnY',
    appId: '1:713159073959:android:f1e8b7ea5f3b560bb8fb82',
    messagingSenderId: '713159073959',
    projectId: 'crudfirey',
    storageBucket: 'crudfirey.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtN8IfRWZCnA9STblG05jfC8gRT1_drZA',
    appId: '1:713159073959:ios:10a38ca3071a944fb8fb82',
    messagingSenderId: '713159073959',
    projectId: 'crudfirey',
    storageBucket: 'crudfirey.appspot.com',
    iosBundleId: 'com.example.crudfirey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoTWoWsC2ngHtEotoW-LXfj6u10sgvNJI',
    appId: '1:713159073959:web:3eb22dbfd40ccd9eb8fb82',
    messagingSenderId: '713159073959',
    projectId: 'crudfirey',
    authDomain: 'crudfirey.firebaseapp.com',
    storageBucket: 'crudfirey.appspot.com',
    measurementId: 'G-H4YLT026C4',
  );
}
